name: CI

on:
  push:
    branches:
      - master
      - 'v[0-9]*'
    tags:
      - 'v[0-9]*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest, windows-latest, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Choose Python version ${{ matrix.python_version }}
        uses: actions/setup-python@v6
        with:
          python-version: '${{ matrix.python_version }}'
          cache: 'pip'
      - run: |
           [[ "${{ matrix.os }}" = "ubuntu-latest" ]] && sudo apt-get install -y libcap-dev || true
        shell: bash
      - name: install tox
        run: python3 -m pip install tox tox-uv
      - name: run tox
        run: tox -e 'py${{ matrix.python_version }}'
      - name: submit code coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  additional:
    strategy:
      matrix:
        envs: ["docs-check"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: 'Choose Python version 3.11'
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: sudo apt-get install -y pandoc libcap-dev
      - name: install tox
        run: python3 -m pip install tox tox-uv
      - name: 'run tox for environment ${{ matrix.envs }}'
        run: tox -e '${{ matrix.envs }}'
      - name: submit code coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: 'Choose Python version 3.11'
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: sudo apt-get install -y pandoc
      - name: install tox
        run: python3 -m pip install tox tox-uv
      - name: 'run tox for docs-build-ci'
        run: tox -e 'docs-build-ci'
      - uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: 'docs/build/html/'

  deploy-docs:
    runs-on: ubuntu-latest
    needs: [build-docs, additional, tests]
    if: github.ref  == 'refs/heads/master'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - run: |
          curl -XPOST -u "sk1p:${{secrets.PAGES_TRIGGER_GH_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H 'Content-Type: application/json' https://api.github.com/repos/LiberTEM/libertem.github.io/dispatches --data '{"event_type":"build_pages","client_payload":{"from":"LiberTEM-live"}}'

  release:
    runs-on: ubuntu-latest
    needs: [tests, additional]
    # master branch, stable branches or release tags:
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/v') || github.ref == 'refs/heads/master'
    env:
      LT_RELEASE_UPLOAD_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LT_RELEASE_UPLOAD_PYPI_PASSWORD: ${{ secrets.LT_RELEASE_UPLOAD_PYPI_PASSWORD }}
      LT_RELEASE_UPLOAD_ZENODO_TOKEN: ${{ secrets.LT_RELEASE_UPLOAD_ZENODO_TOKEN }}
      LT_RELEASE_UPLOAD_ZENODO_CONCEPT: ${{ secrets.LT_RELEASE_UPLOAD_ZENODO_CONCEPT }}
    steps:
      - uses: actions/checkout@v6
      - name: Choose Python version 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: install release script deps
        run: pip install -r scripts/requirements.txt
      - name: release status
        run: ./scripts/release status
      - name: run release script
        run: ./scripts/release --verbose upload --no-dry-run --pypi-user __token__
